# Generated by Django 3.2.23 on 2024-01-30 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuserservice_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='clientAPIKey',
        ),
        migrations.RemoveField(
            model_name='service',
            name='clientID',
        ),
        migrations.AddField(
            model_name='customuserservice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='customuserservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_credentials',
            field=models.JSONField(default=True, verbose_name='Данные сервиса'),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuserservice',
            name='customUser',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuserservice',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=12, null=True, verbose_name='Имя'),
        ),
    ]
