# Generated by Django 3.2.23 on 2024-01-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20240130_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
