# Generated by Django 3.2.23 on 2024-01-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuserservice_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_credentials',
        ),
        migrations.AddField(
            model_name='customuserservice',
            name='service_credentials',
            field=models.JSONField(default=True, verbose_name='Данные сервиса'),
        ),
    ]
