# Generated by Django 3.2.23 on 2024-02-05 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20240130_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuserservice',
            options={'verbose_name': 'Сервис пользователя', 'verbose_name_plural': 'Сервисы пользователей'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Сервис', 'verbose_name_plural': 'Сервисы'},
        ),
        migrations.AlterField(
            model_name='customuserservice',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.service', unique=True),
        ),
    ]
